[package]
name = "goswid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbor = "0.4.1"
rustc-serialize = "0.3"
serde_cbor = "0.10"
